config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  resources :products
  resources :users

  resources :order_items


  get 'cart' => 'cart#show'
  get 'signup' => 'users#new'
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  get 'search' => 'products#search'
  post '/cart' => 'order_items#destroy'
  post 'checkout/create' => 'checkout#create', as: "checkout_create"
  delete '/logout' => 'sessions#destroy'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  before_save :set_subtotal


  def subtotal
    order_items.collect {|order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0}.sum
  end
  #Ternary operator^

private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total


  def unit_price
    #if there is a record....
    if persisted?
      self[:unit_price]
    else
      product.actual_price
    end
  end

  def total
    return unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_items
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :orders, dependent: :destroy #destroying associated records when parent is removed (delete account button)

  validates :email, uniqueness: true, presence: true

  validates_presence_of :first_name,
                      :last_name,
                      :password_digest

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper



  # I added this code below to handle a safe redirect when user inputs incorrect credentials
  rescue_from ActionController::Redirecting::UnsafeRedirectError do
    redirect_to root_url
  end


  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
  end

  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

#requires user to have an account and be signed in to be able to see cart
before_action :require_user, only:[:show]

  def show
    @order_items = current_order.order_items
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController


  def create
    @session = Stripe::Checkout::Session.create({

    shipping_address_collection: {
    allowed_countries: ['US', 'CA'],
    },
    shipping_options: [
    {
      shipping_rate_data: {
        type: 'fixed_amount',
        fixed_amount: {
          amount: 0,
          currency: 'usd',
        },
        display_name: 'Free shipping',
        # Delivers between 5-7 business days
        delivery_estimate: {
          minimum: {
            unit: 'business_day',
            value: 5,
          },
          maximum: {
            unit: 'business_day',
            value: 7,
          },
        }
      }
    },
    {
      shipping_rate_data: {
        type: 'fixed_amount',
        fixed_amount: {
          amount: 1500,
          currency: 'usd',
        },
        display_name: 'Next day air',
        # Delivers in exactly 1 business day
        delivery_estimate: {
          minimum: {
            unit: 'business_day',
            value: 1,
          },
          maximum: {
            unit: 'business_day',
            value: 1,
          },
        }
      }
    },
    ],
      client_reference_id: current_user.id,
      success_url: root_url,
      cancel_url: cart_url,
      payment_method_types: ['card'],
      line_items: [
          name: "Best Samples Ever",
          amount: (current_order.subtotal * 100).to_i,
          currency: "usd",
          quantity: 1,
      ],
      mode: 'payment',
      metadata: {product_id: params[:product_id]},
      customer_email: current_user.email,
    })

#   respond_to do |format|
#      format.js
#    end
    redirect_to @session.url, allow_other_host: true
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order

  protect_from_forgery with: :null_session

# This would be good to keep for orders page in future
#    def index
#      @user = current_user
#      @order_item = @user.order_items
#    end


  def create
    @order_item = @order.order_items.new(order_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order_item = @order.order_items.find(params[:id])
    @order_item.update(order_params)
    @order_items = current_order.order_items
    redirect_to cart_path
    flash[:notice] = "Shopping cart was successfully updated"
  end

  def destroy
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = current_order.order_items
    redirect_to cart_path
    flash[:alert] = "Shopping cart items deleted"
  end


private

  def order_params
    params.require(:order_item).permit(:product_id, :quantity)
  end

  def set_order
    @order = current_order
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def show
    @product = Product.find(params[:id])
    @order_item = current_order.order_items.new
  end

  def search
    @products = Product.where("title LIKE ?" ,"%" + params[:q] + "%")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end


  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
      flash[:notice] = "Logged in successfully"
    else
      redirect_to '/login'
      flash[:alert] = "Invalid email or password"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
    flash[:notice] = "Logged out successfully"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @users = User.new
  end

  def create
    @user = User.new(user_params)
  if @user.save
    session[:user_id] = @user.id
    redirect_to '/'
    flash[:notice] = "Account successfully created"
  else
    redirect_to '/signup'
    flash[:alert] = "Invalid data in one or more fields"
    end
  end


  def edit
    @user = User.find(params[:id])
  end


  def update_password
   @user = current_user
   @user.update(update_pass_params)
   if @user.save
     flash[:notice] = "Password successfully updated"
     redirect_to edit_user_path
   else
     flash[:alert] = "Password was not updated"
     redirect_to edit_user_path
   end
  end


  def destroy
   @user = User.find(params[:id])
   @user.destroy
   flash[:notice] = "Account successfully deleted"
   redirect_to '/'
  end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def update_pass_params
    params.permit(:password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    # Using Find by id to avoid potential errors
    if session[:order_id] && Order.find(session[:order_id])
      Order.find(session[:order_id])
    else
      Order.create user_id: session[:user_id]
    end
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart/_cart_items.html.erb
<div class="span6 pull-right" style="text-align:right;position:relative;top:33px;">
  <%= link_to("Continue Shopping", products_url) %>
</div>

<h1 style="color:orange;"><strong>Shopping Cart</h1>
<br>
<br>
<br>
<% @order_items.each do |item| %>
  <h3 style="color:white;"><%= item.product.title%></h3>
  <h4 style="color:white;">$<%=item.product.actual_price %></h4>
  <%= form_with model: item do |f| %>
    <%= f.hidden_field :product_id, value: item.product.id %>
    <%= f.number_field :quantity, value: item.quantity.to_i%>
    <h5 style="position:relative;left:190px;bottom:30px;"><%= f.submit "Update Cart" %></h5>
  <% end %>
  <h5 style="position:relative;left:320px;bottom:68px;"><%= button_to "Remove Items", item, url: order_item_path(item), method: "delete" %></h5>
  <h4 style="color:white;">Subtotal: $<%= item.total %></h4>
  <br>
  <br>
  <br>
<% end %>

<%if current_order.subtotal > 0 %>
<%= button_to "Submit Payment",checkout_create_path %>

<%else%>

<%end%>

<h3 style="color:white;">Your current order has a total of: $<%= current_order.subtotal %></h3>

app/views/cart/show.html.erb
<div id="cart-item">
  <%= render 'cart_items' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Samplezon</title>
    <link rel="stylesheet" href="http://content.codecademy.com/projects/bootstrap.min.css">
    <link href='http://fonts.googleapis.com/css?family=Roboto:100,300,400,700,500' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
    <div class="header">
      <div class="container">
        <div class="navbar">

          <%# This is the logo at the top of the home page %>
            <a href="/"><img class="logo" src="https://i.imgur.com/susZNnd.png"/></a>

            <%# This is the searchbar at the top of the home page %>
              <form id="form" class="d-flex" action="/search">
                <input type="search" class="form-control mr-sm-2" id="query" size="50" name="q" placeholder="Search...">
                <button class="btn btn-warning my-2 my-sm-0">Search</button>
              </form>


              <div class="responsive" style="position:relative;top:20px;">
                <% if current_user %>
                  <ul class="d-flex">
                    <%= link_to "Log out", logout_path, method: "delete", class: "btn btn-warning", style: "position:relative;bottom:10px;left:211px" %></li>
                    <%= link_to "Account Settings", edit_user_path(current_user), {:style=>'position:relative;right:70px;top:35px;'} %>
                    <%= link_to "My Cart (#{current_order.order_items.size})", cart_path, {:style=>'position:relative;top:35px;right:0px'} %>
                  </ul>
                <% else %>
                  <ul class="d-flex">
                    <li><%= link_to "Signup", '/signup', class: "btn btn-warning", style: "position:relative;bottom:10px;" %></li>&nbsp;
                    <li><%= link_to "Login", '/login', class: "btn btn-warning", style: "position:relative;bottom:10px;" %></li>&nbsp;
                  </ul>
                <% end %>
              </div>
          </div>


            <a id="nothing" style="font-weight:bold; color:white; text-decoration:none; font-family:Verdana;" href="#">Departments</a>&nbsp;&nbsp;&nbsp;&nbsp;
            <a id="nothing" style="text-decoration:none; font-family:Verdana;" href="#">Products</a>&nbsp;&nbsp;&nbsp;&nbsp;
            <a id="nothing" style="text-decoration:none;font-family:Verdana;" href="#">Best Sellers</a>&nbsp;&nbsp;&nbsp;&nbsp;
            <a id="nothing" style="text-decoration:none;font-family:Verdana;" href="#">New Releases</a>&nbsp;&nbsp;&nbsp;&nbsp;
          </div>

          <div class="main">
            <div class="container">
            <%= render partial: "shared/flash" %>
                <%= yield %>
                <br><br>
              </div>
            </div>
            <div class="footer">
              <div class="container">
                <div class="col-md-2">
                  <h3>Samplezon</h3>
                  <ul>
                    <li>
                      <a href="#">Install</a>
                    </li>
                    <li>
                      <a href="#">Mobile</a>
                    </li>
                  </ul>
                </div>
                <div class="col-md-2">
                  <ul>
                    <h3>About</h3>
                    <li>
                      <a href="#">Blog</a>
                    </li>
                    <li>
                      <a href="#">Team</a>
                    </li>
                    <li>
                      <a href="#">Jobs</a>
                    </li>
                  </ul>
                </div>
                <div class="col-md-2">
                  <ul>
                    <h3>Support</h3>
                    <li>
                      <a href="#">Help Center</a>
                    </li>
                    <li>
                      <a href="#">Get Started</a>
                    </li>
                    <li>
                      <a href="#">Contact Us</a>
                    </li>
                  </ul>
                </div>
                <div class="col-md-2">
                  <ul>
                    <h3>Community</h3>
                    <li>
                      <a href="#">Facebook</a>
                    </li>
                    <li>
                      <a href="#">Twitter</a>
                    </li>
                    <li>
                      <a href="#">Google+</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>

          </body>
        </html>

app/views/products/index.html.erb
<!-- attempt to make banner image to fill header div -->
<div class="jumbotron jumbotron-fluid" style="background-image:url(https://i.imgur.com/o0hY0uc.jpeg);background-size:cover;">
  <div class=".container">
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  </div>
</div>
<br>
<br>
<br>

<h6 style="color:white; text-align:center">
  2022 Melody Collection OUT NOW!</h6>
<iframe
  width="100%"
  height="300"
  scrolling="no"
  frameborder="no"
  allow="autoplay"
  src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1195245076&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>
<div
  style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;">
  <a href="https://soundcloud.com/cymaticsfm" title="Cymatics.fm" target="_blank" style="color: #cccccc; text-decoration: none;">Cymatics.fm</a>
  ·
  <a href="https://soundcloud.com/cymaticsfm/cymatics-2022-melody-collection" title="2022 Melody Collection (OUT JAN 21)" target="_blank" style="color: #cccccc; text-decoration: none;">2022 Melody Collection (OUT JAN 21)</a>
</div>

<br>
<br>
<br>

<div class="product-list" style="display:grid; grid-template-columns:repeat(auto-fill, minmax(200px, 1fr)); gap:15px;">
  <%-@products.each do |product| %>
    <div class="product card text-center border-white" style="width:200px; background-color:transparent;">
      <%= link_to(product) do %>
      <img class="card-img-top" src="<%= product.cover%>" alt="Sample Pack Picture">
      <div class="card-body">
        <h5 class="card-title" style="color:white; text-decoration:none"><%=product.title%></h5>
        <p class="card-text" style="color:white;text-decoration:none">$<%=product.actual_price%></p>
        <a href="/products/<%=product.id%>" class="btn btn-warning">Show More</a>
      </div>
     <%end%>
   </div>
  <%end%>
</div>

app/views/products/search.html.erb
<div class="span6 pull-right" style="text-align:right">
  <%= link_to("Products Page", {:action => 'index'}) %>
</div>

<h1 style="color: white;">
  Search Results
</h1>
<br>

<% if @products.empty? %>
  <h2 style="color: red;">
    No results found ;(
  </h2>
<%else%>
<div class="product-list" style="display:grid; grid-template-columns:repeat(auto-fill, minmax(200px, 1fr)); gap:15px;">
<%-@products.each do |product| %>
  <div class="product card text-center border-white" style="width:200px; background-color:transparent;">
    <%= link_to(product) do %>
    <img class="card-img-top" src="<%= product.cover%>" alt="Sample Pack Picture">
    <div class="card-body">
      <h5 class="card-title" style="color:white; text-decoration:none"><%=product.title%></h5>
      <p class="card-text" style="color:white;text-decoration:none">$<%=product.actual_price%></p>
    </div>
   <%end%>
  </div>
 <%end%>
<%end%>

app/views/products/show.html.erb
<div class="span6 pull-right" style="text-align:right;position:relative;top:33px;;">
  <%= link_to("Products Page", {:action => 'index'}) %>
</div>

<div class="show row">
  <div class="cover col-md-4">
    <img src="<%=@product.cover%>">
  </div>

  <div class="col-sm-8">
    <h3 class="product-title" style="color:silver;"><%=@product.title %></h3>
    <p class="product-description" style="color:silver;"><%= @product.description %></p>
    <p class="product-price" style="color:silver; text-decoration:line-through;">List Price: <%= @product.price %></p>
    <p class="product-actual-price" style="color:red;">Our Price: $<%= @product.actual_price%></p>
<% if current_user %>
    <%= form_with model: @order_item do |f| %>
    <%= f.hidden_field :product_id, value: @product.id %>
    <%= f.number_field :quantity, value: 1, min: 1%>
    <%= f.submit "Add To Cart" %>
    <%end%>
<% else %>

<% end %>
  </div>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-success mt-4" role="alert">
  <%= flash[:notice] %>
</div>
<%end%>

<% if flash[:alert] %>
<div class="alert alert-danger mt-4" role="alert">
  <%= flash[:alert] %>
</div>
<%end%>

app/views/users/edit.html.erb
<h2 style="color:white;"><strong>Account: <%=@user.email%></h2>

<br>
<br>
<% provide(:title, "Edit user") %>
<h4 style="color:white;">Update Password</h4>

<div class="row">
  <div class="col-md-6 col-md-offset-3" style="color:white;">
    <%= form_for(@user) do |f| %>
      <%= f.label "New Password" %>
      <%= f.password_field class: 'form-control' %>

      <%= f.label "Re-enter password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Update Password", class: "btn btn-warning" %>
    <% end %>
  </div>
</div>

<br>
<br>
<br>

<h4 style="color:white;">Delete Account</h4>


<div class="row">
  <div class="col-md-6 col-md-offset-3" style="color:white;">
    <%= form_for(@user) do |f| %>
    <%= button_to "Delete Account", {:controller => 'users', :action => 'destroy'}, :method => :delete, :class => "btn btn-danger" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">

    <h1>Sign up</h1>
    <%= form_for(@users) do |f| %>
    <%= f.text_field :first_name, :placeholder => "First Name" %>
    <%= f.text_field :last_name, :placeholder => "Last Name" %>
    <%= f.email_field :email, :placeholder => "Email" %>
    <%= f.password_field :password, :placeholder => "Password" %>
    <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation" %>
    <%= f.submit "Create an account", class: "btn btn-warning" %>
  <% end %>
    </div>
  </div>
</div>